package org.jcmpj.trt15.view;

import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jcmpj.trt15.controller.AcessarWebTRT15;
import org.jcmpj.trt15.controller.AtualizarBancoDados;
import org.jcmpj.trt15.model.DBManager;
import org.jcmpj.trt15.resources.Global;

/**
 *
 * @author jcmpj
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        initializeFiles();
        setIcon();
        pb01.setVisible(false);        
    }

    //SwingUtilities.invokeLater()
    public void setStatus(String text) {
        new Thread() {
            @Override
            public void run() {
                txtAtualizando.setText(text);
                repaint();
            }
        }.start();
    }
    
    public void atualizarDados() {
        new Thread() {
            @Override
            public void run() {
                txtAtualizando.setText("Atualizando ...");
                pb01.setVisible(true);
                repaint();
                iniciarAtualizacao();
            }
        }.start();        
    }
    
    public void iniciarAtualizacao() {
        AcessarWebTRT15 thread1 = new AcessarWebTRT15("Arquivo Texto", this);
        AtualizarBancoDados thread2 = new AtualizarBancoDados("Atualiza Banco", this);        
        
        Thread t1 = new Thread(thread1);
        Thread t2 = new Thread(thread2);
        
        t1.start();
        try {
            t1.join();
        } catch (InterruptedException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        t2.start();
        try {
            t2.join();
            Thread.sleep(50);
        } catch (InterruptedException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        /**
         * setStatus("Atualizado. FIM!"); pb01.setVisible(false);
         */
        MainWindow mw = new MainWindow();
        mw.inicializar();
        mw.setVisible(true);
        this.dispose();
    }
    
    private void continuarSemAtualizar() {
        MainWindow mw = new MainWindow();
        mw.inicializar();
        mw.setVisible(true);
        this.dispose();
    }
    
    public static void initializeFiles() {
        /**
         * StringBuilder sb = new StringBuilder();
         *
         * sb.append(System.getProperty("user.home"));
         * sb.append(System.getProperty("file.separator"));
         * sb.append("Documentos");
         * sb.append(System.getProperty("file.separator"));
         * sb.append("Laudos-TRT"); sb.append(File.separator); String aux = new
         * String(sb); File strPath = new File(aux); String pathToDataFile = aux
         * + "dataFile.txt"; String pathToLaudo = aux + "laudo.db";
         */
        File strPath = new File(Global.getPathAux());
        File dataFile = new File(Global.getPathDataFile());
        File laudoFile = new File(Global.getPathLaudoDbFile());
        
        if (!Files.exists(Paths.get(Global.getPathAux()))) {
            boolean mkdirs = strPath.mkdirs();
        }
        
        if (!dataFile.exists()) {
            try {
                dataFile.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        if (!laudoFile.exists()) {
            //laudoFile.mkdirs();
            if (DBManager.createNewDatabase()) {
                DBManager.createNewTable();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAtualizando = new javax.swing.JLabel();
        pb01 = new javax.swing.JProgressBar();
        btnNaoAtualizar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Laudos TRT");
        setAlwaysOnTop(true);
        setName("FrameLaudos"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 300));
        setSize(new java.awt.Dimension(400, 300));

        txtAtualizando.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtAtualizando.setForeground(new java.awt.Color(255, 0, 0));
        txtAtualizando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAtualizando.setFocusable(false);
        txtAtualizando.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        pb01.setFocusable(false);
        pb01.setIndeterminate(true);
        pb01.setMaximumSize(new java.awt.Dimension(400, 4));

        btnNaoAtualizar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnNaoAtualizar.setText("Continuar sem atualizar");
        btnNaoAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNaoAtualizarActionPerformed(evt);
            }
        });

        btnAtualizar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnAtualizar.setText("Atualizar os dados");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNaoAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addComponent(pb01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAtualizando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAtualizando, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pb01, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(btnNaoAtualizar)
                .addGap(20, 20, 20))
        );

        setSize(new java.awt.Dimension(440, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNaoAtualizarActionPerformed
        continuarSemAtualizar();
    }//GEN-LAST:event_btnNaoAtualizarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        atualizarDados();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Inicio().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnNaoAtualizar;
    private javax.swing.JProgressBar pb01;
    private javax.swing.JLabel txtAtualizando;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/ico-jc.png")));
    }
}
