package org.jcmpj.trt15.view;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.jcmpj.trt15.controller.PreencherForm;
import org.jcmpj.trt15.model.DBManager;
import org.jcmpj.trt15.resources.WindowManager;

/**
 *
 * @author jcmpj
 */
public class Listagem extends javax.swing.JInternalFrame {

    private WindowManager windowManager;
    private static Listagem listagem;
    public PreencherForm pf;

    public List<Map<String, ?>> procs;

    public static Listagem getInstance() {
        if (listagem == null) {
            listagem = new Listagem();
        }
        return listagem;
    }

    /**
     * Creates new form Listagem
     */
    public Listagem() {
        initComponents();
        pf = new PreencherForm(this);
        LoadTable();
    }

    public void LoadTable() {
        PreencherForm pf = new PreencherForm(this);
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Id", "Processo", "Reclamante", "Reclamada"}, 0);
        try {
            procs = DBManager.rsToList();
            for (Map proc : procs) {
                Object linha[] = new Object[]{proc.get("id"),
                    proc.get("numProcesso"),
                    proc.get("nomeReclamante"),
                    proc.get("nomeReclamada")};

                modelo.addRow(linha);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Listagem.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblProcessos.setModel(modelo);
        tblProcessos.getColumnModel().getColumn(0).setMaxWidth(0);
        tblProcessos.getColumnModel().getColumn(0).setMinWidth(0);
        tblProcessos.getColumnModel().getColumn(0).setPreferredWidth(0);
        tblProcessos.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblProcessos.getColumnModel().getColumn(2).setPreferredWidth(400);
        tblProcessos.getColumnModel().getColumn(3).setPreferredWidth(400);
    }

    public void loadTableFilter(String campo, String valor) {
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Id", "Processo", "Reclamante", "Reclamada"}, 0);
        try {
            procs = DBManager.rsListFilter(campo, valor);
            if (procs != null) {
                for (Map proc : procs) {
                    Object linha[] = new Object[]{proc.get("id"),
                        proc.get("numProcesso"),
                        proc.get("nomeReclamante"),
                        proc.get("nomeReclamada")};

                    modelo.addRow(linha);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Listagem.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblProcessos.setModel(modelo);
        tblProcessos.getColumnModel().getColumn(0).setMaxWidth(0);
        tblProcessos.getColumnModel().getColumn(0).setMinWidth(0);
        tblProcessos.getColumnModel().getColumn(0).setPreferredWidth(0);
        tblProcessos.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblProcessos.getColumnModel().getColumn(2).setPreferredWidth(400);
        tblProcessos.getColumnModel().getColumn(3).setPreferredWidth(400);
    }
    
    public void loadTableDateFilter(String dateStart, String dateEnd) {
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Id", "Processo", "Reclamante", "Reclamada"}, 0);
        try {
            procs = DBManager.rsListDateFilter(dateStart, dateEnd);
            if (procs != null) {
                for (Map proc : procs) {
                    Object linha[] = new Object[]{proc.get("id"),
                        proc.get("numProcesso"),
                        proc.get("nomeReclamante"),
                        proc.get("nomeReclamada")};

                    modelo.addRow(linha);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Listagem.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblProcessos.setModel(modelo);
        tblProcessos.getColumnModel().getColumn(0).setMaxWidth(0);
        tblProcessos.getColumnModel().getColumn(0).setMinWidth(0);
        tblProcessos.getColumnModel().getColumn(0).setPreferredWidth(0);
        tblProcessos.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblProcessos.getColumnModel().getColumn(2).setPreferredWidth(400);
        tblProcessos.getColumnModel().getColumn(3).setPreferredWidth(400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane2 = new javax.swing.JScrollPane();
        tblProcessos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtdateStart = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtdateEnd = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBuscaReclamada = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBuscaReclamante = new javax.swing.JTextField();
        btnAplicarFiltro = new javax.swing.JButton();
        btnLimparFiltro = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNumProcesso = new javax.swing.JTextField();
        txtNomeReclamante = new javax.swing.JTextField();
        txtNomeReclamada = new javax.swing.JTextField();
        txtLocalVistoria = new javax.swing.JTextField();
        txtDataVistoria = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtHoraVistoria = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEnderecoVistoria = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPeriodoReclamado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtFuncaoExercida = new javax.swing.JTextField();
        btnSalvarAlteracoes = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);
        setTitle("Listagem dos Processos");

        tblProcessos.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tblProcessos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Processo", "Reclamante", "Reclamada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProcessos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProcessosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProcessos);
        if (tblProcessos.getColumnModel().getColumnCount() > 0) {
            tblProcessos.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "Filtros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 3, 15), new java.awt.Color(0, 153, 153))); // NOI18N

        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 100, 0};
        jPanel3Layout.rowHeights = new int[] {0, 2, 0, 2, 0};
        jPanel3Layout.columnWeights = new double[] {0.2, 0.3, 0.3, 0.2};
        jPanel3Layout.rowWeights = new double[] {0.5, 0.5, 0.5};
        jPanel3.setLayout(jPanel3Layout);

        jLabel5.setText("<html>Período: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Inicio    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel5, gridBagConstraints);

        try {
            txtdateStart.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdateStart.setToolTipText("dd/mm/aaaa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(txtdateStart, gridBagConstraints);

        jLabel6.setText("   Fim   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jLabel6, gridBagConstraints);

        try {
            txtdateEnd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdateEnd.setToolTipText("dd/mm/aaaa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(txtdateEnd, gridBagConstraints);

        jLabel7.setText("Reclamada:   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel7, gridBagConstraints);

        txtBuscaReclamada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaReclamadaKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(txtBuscaReclamada, gridBagConstraints);

        jLabel8.setText("Reclamante:   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel8, gridBagConstraints);

        txtBuscaReclamante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaReclamanteKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(txtBuscaReclamante, gridBagConstraints);

        btnAplicarFiltro.setText("Aplicar Filtro");
        btnAplicarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarFiltroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        jPanel3.add(btnAplicarFiltro, gridBagConstraints);

        btnLimparFiltro.setText("Limpar Filtro");
        btnLimparFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFiltroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        jPanel3.add(btnLimparFiltro, gridBagConstraints);

        btnProximo.setText("Próximo");
        btnProximo.setEnabled(false);
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnProximo)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProximo))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "Dados Básicos do Laudo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 3, 15), new java.awt.Color(0, 153, 153))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 100, 0};
        jPanel1Layout.rowHeights = new int[] {0, 25, 0, 25, 0, 25, 0, 25, 0};
        jPanel1Layout.columnWeights = new double[] {0.2, 4.0, 1.5, 4.0};
        jPanel1Layout.rowWeights = new double[] {1.0, 1.0, 1.0, 1.0, 1.0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setText("N° do Processo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Reclamante:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Reclamada:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Data da vistoria:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel9.setText("Local da vistoria:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        jPanel1.add(jLabel9, gridBagConstraints);

        txtNumProcesso.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(txtNumProcesso, gridBagConstraints);

        txtNomeReclamante.setEditable(false);
        txtNomeReclamante.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNomeReclamante.setPreferredSize(new java.awt.Dimension(180, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(txtNomeReclamante, gridBagConstraints);

        txtNomeReclamada.setEditable(false);
        txtNomeReclamada.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(txtNomeReclamada, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(txtLocalVistoria, gridBagConstraints);

        try {
            txtDataVistoria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataVistoria.setToolTipText("dia/mês/ano");
        txtDataVistoria.setMinimumSize(new java.awt.Dimension(100, 24));
        txtDataVistoria.setPreferredSize(new java.awt.Dimension(100, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(txtDataVistoria, gridBagConstraints);

        jLabel10.setText("Hora da Vistoria:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel10, gridBagConstraints);

        try {
            txtHoraVistoria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## : ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(txtHoraVistoria, gridBagConstraints);

        jLabel11.setText("Endereço vistoria:,");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        jPanel1.add(jLabel11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(txtEnderecoVistoria, gridBagConstraints);

        jLabel12.setText("Período reclamado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        jPanel1.add(jLabel12, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(txtPeriodoReclamado, gridBagConstraints);

        jLabel13.setText("Função exercida:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        jPanel1.add(jLabel13, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(txtFuncaoExercida, gridBagConstraints);

        btnSalvarAlteracoes.setText("Salvar Alterações");
        btnSalvarAlteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlteracoesActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnSalvarAlteracoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(60, 60, 60))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarAlteracoes)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setBounds(0, 0, 1024, 603);
    }// </editor-fold>//GEN-END:initComponents

    private void tblProcessosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProcessosMouseClicked
        pf.FillFormData();
        btnProximo.setEnabled(true);
        MainWindow.abrirDocumentoMenuItem.setEnabled(true);
        MainWindow.btnDadosBasicos.setEnabled(true);
        MainWindow.btnAtividades.setEnabled(true);
        MainWindow.btnAcompanhantes.setEnabled(true);
        MainWindow.btnQuesitos.setEnabled(true);
        MainWindow.btnAbrirLaudo.setEnabled(true);
    }//GEN-LAST:event_tblProcessosMouseClicked

    private void btnSalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlteracoesActionPerformed
        pf.saveFormData();

    }//GEN-LAST:event_btnSalvarAlteracoesActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        if (windowManager == null) {
            windowManager = new WindowManager(getDesktopPane());
        }
        windowManager.openWindow(Atividades.getInstance());
    }//GEN-LAST:event_btnProximoActionPerformed

    private void txtBuscaReclamadaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaReclamadaKeyReleased
        loadTableFilter("nomeReclamada", txtBuscaReclamada.getText());
    }//GEN-LAST:event_txtBuscaReclamadaKeyReleased

    private void txtBuscaReclamanteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaReclamanteKeyReleased
        loadTableFilter("nomeReclamante", txtBuscaReclamante.getText());
    }//GEN-LAST:event_txtBuscaReclamanteKeyReleased

    private void btnAplicarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarFiltroActionPerformed
        loadTableDateFilter(txtdateStart.getText(), txtdateEnd.getText());
    }//GEN-LAST:event_btnAplicarFiltroActionPerformed

    private void btnLimparFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFiltroActionPerformed
        LoadTable();
    }//GEN-LAST:event_btnLimparFiltroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicarFiltro;
    private javax.swing.JButton btnLimparFiltro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvarAlteracoes;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tblProcessos;
    private javax.swing.JTextField txtBuscaReclamada;
    private javax.swing.JTextField txtBuscaReclamante;
    public javax.swing.JFormattedTextField txtDataVistoria;
    public javax.swing.JTextField txtEnderecoVistoria;
    public javax.swing.JTextField txtFuncaoExercida;
    public javax.swing.JFormattedTextField txtHoraVistoria;
    public javax.swing.JTextField txtLocalVistoria;
    public javax.swing.JTextField txtNomeReclamada;
    public javax.swing.JTextField txtNomeReclamante;
    public javax.swing.JTextField txtNumProcesso;
    public javax.swing.JTextField txtPeriodoReclamado;
    private javax.swing.JFormattedTextField txtdateEnd;
    private javax.swing.JFormattedTextField txtdateStart;
    // End of variables declaration//GEN-END:variables
}
