package org.jcmpj.trt15.view;

import java.awt.event.KeyEvent;
import java.util.Map;
import javax.swing.JOptionPane;
import org.jcmpj.trt15.controller.PreencherForm;
import org.jcmpj.trt15.model.DBManager;
import org.jcmpj.trt15.resources.WindowManager;

/**
 *
 * @author jcmpj
 */
public class Quesitos extends javax.swing.JInternalFrame {

    private WindowManager windowManager;
    private String id;
    private static Quesitos quesitos;

    public static Quesitos getInstance() {
        if (quesitos == null) {
            quesitos = new Quesitos();
        } else {
            quesitos.loadInitialData();
        }
        return quesitos;
    }

    /**
     * Creates new form Atividades
     */
    public Quesitos() {
        initComponents();
        loadInitialData();
    }

    private void loadInitialData() {
        Map<String, String> dl = PreencherForm.getLaudoIdNumProcesso();

        id = dl.get("id");
        String numProcessos = dl.get("numProcesso");
        String nomeReclamante = dl.get("nomeReclamante");
        String nomeReclamada = dl.get("nomeReclamada");

        // txtReclamada.setText("Reclamada: " + nomeReclamada);
        // txtReclamante.setText("Reclamante: " + nomeReclamante);
        String titReclamante;
        titReclamante = "Quesitos reclamante: " + nomeReclamante;
        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(
                new java.awt.Color(0, 153, 153)), titReclamante,
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Liberation Sans", 3, 15),
                new java.awt.Color(0, 153, 153)));

        String titReclamada;
        titReclamada = "Quesitos reclamada: " + nomeReclamada;
        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(
                new java.awt.Color(0, 153, 153)), titReclamada,
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Liberation Sans", 3, 15),
                new java.awt.Color(0, 153, 153)));

        Map<String, String> txt = DBManager.getQuesitos(id);
        txtAreaQuesitosReclamante.setText(txt.get("quesitosReclamante"));
        txtAreaQuesitosReclamada.setText(txt.get("quesitosReclamada"));
    }
    
    private void addLineBreak(int c, String anterior, String txtArea) {
        String txt = anterior.trim() + "\n";
        //txt = txt.trim();
        if (c == KeyEvent.VK_ENTER) {
            if (txtArea.equalsIgnoreCase("txtAreaQuesitosReclamante")) {
                txtAreaQuesitosReclamante.setText(txt);
            } else if (txtArea.equalsIgnoreCase("txtAreaQuesitosReclamada")) {
                txtAreaQuesitosReclamada.setText(txt);
            }
        }
    }
    
    private void saveText() {
        boolean up;
        up = DBManager.updateQuesitos(txtAreaQuesitosReclamante.getText(), txtAreaQuesitosReclamada.getText(), Integer.parseInt(id));
        if (up) {
            JOptionPane.showMessageDialog(null, "Texto Atualizados\nno banco de dados", "Update", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Erro\nbanco de dados", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalvarAtividades = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaQuesitosReclamante = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaQuesitosReclamada = new javax.swing.JTextArea();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Acompanhantes / Testemunhas");
        setPreferredSize(new java.awt.Dimension(1024, 603));

        jPanel1.setLayout(new java.awt.BorderLayout());

        btnSalvarAtividades.setText("Salvar Alterações");
        btnSalvarAtividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAtividadesActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvarAtividades, java.awt.BorderLayout.CENTER);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "Quesitos Reclamante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 3, 18), new java.awt.Color(0, 153, 153))); // NOI18N

        txtAreaQuesitosReclamante.setColumns(20);
        txtAreaQuesitosReclamante.setRows(5);
        txtAreaQuesitosReclamante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAreaQuesitosReclamanteKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(txtAreaQuesitosReclamante);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "Quesitos Reclamada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 3, 18), new java.awt.Color(0, 153, 153))); // NOI18N

        txtAreaQuesitosReclamada.setColumns(20);
        txtAreaQuesitosReclamada.setRows(5);
        txtAreaQuesitosReclamada.setBorder(null);
        txtAreaQuesitosReclamada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAreaQuesitosReclamadaKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(txtAreaQuesitosReclamada);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarAtividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAtividadesActionPerformed
        saveText();
    }//GEN-LAST:event_btnSalvarAtividadesActionPerformed

    private void txtAreaQuesitosReclamanteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaQuesitosReclamanteKeyReleased
        addLineBreak(evt.getKeyCode(), txtAreaQuesitosReclamante.getText(), "txtAreaReclamante");
    }//GEN-LAST:event_txtAreaQuesitosReclamanteKeyReleased

    private void txtAreaQuesitosReclamadaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaQuesitosReclamadaKeyReleased
        addLineBreak(evt.getKeyCode(), txtAreaQuesitosReclamada.getText(), "txtAreaReclamda");
    }//GEN-LAST:event_txtAreaQuesitosReclamadaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarAtividades;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea txtAreaQuesitosReclamada;
    private javax.swing.JTextArea txtAreaQuesitosReclamante;
    // End of variables declaration//GEN-END:variables
}
